### ISSUE TITLE
does not keep count forever

### ISSUE THREAD

**Issue by tregonzales** [dodekeract/atom-count#1]
count resets after quitting aotm

**Comment by FlorianWendelborn** [comment]
@tregonzales I'm aware of the issue. However, I'm not aware of the solution. The API I'm using to "permanently" store the count **should not** reset upon restarting, and actually **doesn't always** do that. It's really weird and I'm not sure how to solve it properly. Might even be an upstream bug.

**Comment by FlorianWendelborn** [comment]
@tregonzales it's an ugly hack, but I'm saving the key count in the config now. Should be completely persistent now. I don't like the solution, but it's the best I can do.

In addition to that, I added Mac key support (⇧⌘C etc.) to the formatter.

Please let me know if `v2.0.0` works for you.
